### PR TITLE
The Panic Attack

### PR DESCRIPTION
**Pull request by StarInAPond**
New Panic Attack is fine, old version just doesn't work well with vsh, loading shells leaves you very vulnerable, there's no real benefit, it's barely faster than shooting manually

### CODE REVIEW

**Review by FortyTwoFortyTwo — COMMENTED** [review]
I made changes to Panic Attack because of how identical Shotgun is.

This weapon could have different stats, if current vsh stats were to stay I would've just suggest increasing fire rate very high.

**Comment by StarInAPond** [comment]
Maybe add something else to the new one?
Old just doesn't work due to spread, slow load and slow fire rate, you also can't change weapons while shooting, purely short range shotgun

**Comment by Mikusch** [comment]
> I made changes to Panic Attack because of how identical Shotgun is.

It has different stats, I wouldn't call that identical. The weapon doesn't need to be different than it is in the regular game, there is absolutely no point in that.

As it is right now, it's pretty much unusable. Too slow and sluggish, basically just dead weight in your loadout.

**Comment by FortyTwoFortyTwo** [comment]
> The weapon doesn't need to be different than it is in the regular game, there is absolutely no point in that.
A lot of VSH weapons already have some changes that some may seems not worth to change anyway. For this weapon, I'm okay with just VSH changes removed, but I just think this could also be the moment to have new different stats instead.

I don't think any of us have solid idea on what new stats could be given, it can be anything, or I can just take the normal stats

**Review by FortyTwoFortyTwo — APPROVED** [review]

**Pull request merged**
